language: php

services:
 - mysql
php:
  - 7.1

before_script:
  - cp .env.travis .env
  - mysql -e 'CREATE DATABASE travis;'
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit